appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ANRS/XXKuFNwI9n3jue/nSvMcf4MKGi+BFoQB5f1fucCeUn18NnYf0y5SNs/LmAoD9+CljOaGQgMGGGDnmSVPVJHFUewryb9kVoYvbpOpxU5pvJg1hWkTSAH6/CQvemQWHOMZK2doL0EgUlqaTZJCw7l57tuZV+vtca8am6QDn/iGZDNMge5n4FANVJNf/xxjgCwSnSzuQm9RE5knrOv/O7BQLf8cLuzDaoEvOx/ekvhmopJoHVaK0lRD9u4BfxuvbkIk8xXXgZgn0LmD2ZF8mZr/n4aoo1ORU4GB/nNL5d+oYBWwxU5k5cZgF6iHTGcx9XhJaokQX1Vk8NKJhc63wzHWgx5XmiFAvCvLgtGqU0ONmXT+ToEQeuYXj1Fbc81bycLtwV/BvohKKyZfIjMmpFq/FPFQiDCSYYZKJldW4G8utvr+F07kjwgo3o4E/Pk1yY81AH+Ry6fDu7es0iyTz5TzCcNqFClC3MknjaiYAFq6E2fXWCJsqv1tU3LYzPr1TgXxgjJE8BCbyWg67BEJWP7b1ZOFsM+9QhBiDK/hXN4ojWL9ujqTz3t31HQFXn/n0MhskYpev85rVfo9kNJzzHDMgr2VDbmRcbXcRF7RUuWnf0/Hmatn3/kZtEksMd5dYQrI+/fcKaAy5miBqap/FhlMeV/HbUpz8djgunitS8=}
