travis:
  secure:
    BINSTAR_TOKEN: WEg5D0D+5vkvYw/SIv6gVZm60qs8EjBlSX2B05sBaA/UUslvpdpZ//PvRgKNxVWfEK3sDsY6gIiIQVdED3Rat2AvaYyWWM3dP04uPO3ZmjUjm7jV3QeMjdo775PN0b/zw3zPwrw4rc5I8e0u/okKq+V1NTlaCReRYUCcLHznevEtTCLoR4CfuVqcBR8Jj5qw27RLOBcF+V83JTjrYpcI4c+i5z9Np2RVqsoBLWhb4/ZYTuWA837pU9niaU+HtVuf9jS8BmO8KWFeqMWspj3SHuyZzm55mG1XuuzlKVhmpfXqG7GLQ/Yfn1tELbMYcIhpeVfdNwpy8LG4+ry8bG4Faj2Wb64AMDCgfpcOTrO9Zi3qZ2Okaz98PuIj7rXzZPsoUDFMR85R+QHijcl6s4Fd5+kTQqNMKXvzsRkmyZbtuqezetcyAS6LnyeuSn+5HS/udetK6dCZUu8fe1BoR1qHq9WSmi0KmXK1G6mQ4VMT22TzmQverP8zMVQw6JobVzXP91xBAbsuywS4v2rZ7VDt+uZXEbdaHRTy83cog6FB2U3dXksumzEdYnFCw8PlJ39xU49jm0q0tp+x1JgWXavKXB98E6rl2Wr1SJ470zshkHZIRfR/cXl3rwxYfiaobH/T4GLXJCWmsFkivCCkwRo5A2jlT4fuyEGwSQit8fiEV3U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
